kind: Service
apiVersion: v1
metadata:
  name: microcks-hub
  labels:
    app: microcks-hub
    container: microcks-hub
    group: microcks
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      name: microcks-hub
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: microcks-hub
    container: microcks-hub
    group: microcks
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: microcks-hub
  labels:
    app: microcks-hub
    container: microcks-hub
    group: microcks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microcks-hub
      deployment: microcks-hub
      container: microcks-hub
      group: microcks
  template:
    metadata:
      labels:
        app: microcks-hub
        deployment: microcks-hub
        container: microcks-hub
        group: microcks
    spec:
      containers:
        - name: microcks-hub
          image: lbroudoux/microcks-hub:latest
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: info
          resources:
            limits:
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: '/healthz'
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 4
            timeoutSeconds: 3
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: '/healthz'
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: '/dev/termination-log'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
